name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/christeventsapi:latest

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/christeventsapi:latest

  deploy-to-app-service:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: christ-events-api
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/christeventsapi:latest
